-- DROP SCHEMA public;

CREATE SCHEMA public AUTHORIZATION pg_database_owner;

-- DROP SEQUENCE public.accounts_id_seq;

CREATE SEQUENCE public.accounts_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.accounts_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE public.accounts_id_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE public.accounts_id_seq TO dev;

-- DROP SEQUENCE public.employees_id_seq;

CREATE SEQUENCE public.employees_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.employees_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE public.employees_id_seq TO postgres;

-- DROP SEQUENCE public.images_id_seq;

CREATE SEQUENCE public.images_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.images_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE public.images_id_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE public.images_id_seq TO dev;

-- DROP SEQUENCE public.login_id_seq;

CREATE SEQUENCE public.login_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.login_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE public.login_id_seq TO postgres;

-- DROP SEQUENCE public.ratings_id_seq;

CREATE SEQUENCE public.ratings_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.ratings_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE public.ratings_id_seq TO postgres;

-- DROP SEQUENCE public.schedule_id_seq;

CREATE SEQUENCE public.schedule_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.schedule_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE public.schedule_id_seq TO postgres;

-- DROP SEQUENCE public.services_id_seq;

CREATE SEQUENCE public.services_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.services_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE public.services_id_seq TO postgres;

-- DROP SEQUENCE public.sessions_id_seq;

CREATE SEQUENCE public.sessions_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.sessions_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE public.sessions_id_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE public.sessions_id_seq TO dev;

-- DROP SEQUENCE public.shops_id_seq;

CREATE SEQUENCE public.shops_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.shops_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE public.shops_id_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE public.shops_id_seq TO dev;

-- DROP SEQUENCE public.users_id_seq;

CREATE SEQUENCE public.users_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 2147483647
	START 1
	CACHE 1
	NO CYCLE;

-- Permissions

ALTER SEQUENCE public.users_id_seq OWNER TO postgres;
GRANT ALL ON SEQUENCE public.users_id_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE public.users_id_seq TO dev;
-- public.accounts definição

-- Drop table

-- DROP TABLE public.accounts;

CREATE TABLE public.accounts (
	id serial4 NOT NULL,
	"userId" int4 NOT NULL,
	"type" varchar(255) NOT NULL,
	provider varchar(255) NOT NULL,
	"providerAccountId" varchar(255) NOT NULL,
	refresh_token text NULL,
	access_token text NULL,
	expires_at int8 NULL,
	id_token text NULL,
	"scope" text NULL,
	session_state text NULL,
	token_type text NULL,
	CONSTRAINT accounts_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.accounts OWNER TO postgres;
GRANT ALL ON TABLE public.accounts TO postgres;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.accounts TO dev;


-- public.images definição

-- Drop table

-- DROP TABLE public.images;

CREATE TABLE public.images (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"path" varchar(100) NOT NULL,
	"type" varchar(10) NOT NULL,
	created_date timestamp DEFAULT now() NOT NULL,
	CONSTRAINT images_pk PRIMARY KEY (id),
	CONSTRAINT images_unique_path UNIQUE (path)
);

-- Permissions

ALTER TABLE public.images OWNER TO postgres;
GRANT ALL ON TABLE public.images TO postgres;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.images TO dev;


-- public.login definição

-- Drop table

-- DROP TABLE public.login;

CREATE TABLE public.login (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	salt varchar(128) NOT NULL,
	password_hash varchar(128) NOT NULL,
	CONSTRAINT login_pk PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.login OWNER TO postgres;
GRANT ALL ON TABLE public.login TO postgres;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.login TO dev;


-- public.sessions definição

-- Drop table

-- DROP TABLE public.sessions;

CREATE TABLE public.sessions (
	id serial4 NOT NULL,
	"userId" int4 NOT NULL,
	expires timestamptz NOT NULL,
	"sessionToken" varchar(255) NOT NULL,
	CONSTRAINT sessions_pkey PRIMARY KEY (id)
);

-- Permissions

ALTER TABLE public.sessions OWNER TO postgres;
GRANT ALL ON TABLE public.sessions TO postgres;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.sessions TO dev;


-- public.users definição

-- Drop table

-- DROP TABLE public.users;

CREATE TABLE public.users (
	id serial4 NOT NULL,
	"name" varchar(255) NULL,
	email varchar(255) NULL,
	"emailVerified" timestamptz NULL,
	image text NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id),
	CONSTRAINT users_unique UNIQUE (email)
);

-- Permissions

ALTER TABLE public.users OWNER TO postgres;
GRANT ALL ON TABLE public.users TO postgres;
GRANT ALL ON TABLE public.users TO dev;


-- public.verification_token definição

-- Drop table

-- DROP TABLE public.verification_token;

CREATE TABLE public.verification_token (
	identifier text NOT NULL,
	expires timestamptz NOT NULL,
	"token" text NOT NULL,
	CONSTRAINT verification_token_pkey PRIMARY KEY (identifier, token)
);

-- Permissions

ALTER TABLE public.verification_token OWNER TO postgres;
GRANT ALL ON TABLE public.verification_token TO postgres;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.verification_token TO dev;


-- public.shops definição

-- Drop table

-- DROP TABLE public.shops;

CREATE TABLE public.shops (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(56) NOT NULL,
	logo_id int4 NULL,
	zip_code varchar(8) NULL,
	city varchar(32) NULL,
	street varchar(64) NULL,
	"number" varchar(10) NULL,
	cnpj varchar(14) NOT NULL,
	active bool DEFAULT false NOT NULL,
	owner_id int4 NOT NULL,
	phone varchar(15) NULL,
	email text NULL,
	openat time NULL,
	closeat time NULL,
	workingdays _text NULL,
	CONSTRAINT shops_pk PRIMARY KEY (id),
	CONSTRAINT shops_unique UNIQUE (cnpj),
	CONSTRAINT shops_images_fk FOREIGN KEY (logo_id) REFERENCES public.images(id),
	CONSTRAINT shops_users_fk FOREIGN KEY (owner_id) REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Permissions

ALTER TABLE public.shops OWNER TO postgres;
GRANT ALL ON TABLE public.shops TO postgres;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.shops TO dev;


-- public.employees definição

-- Drop table

-- DROP TABLE public.employees;

CREATE TABLE public.employees (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	shopid int4 NOT NULL,
	"name" varchar(256) NOT NULL,
	imageid int4 NULL,
	starthour time NOT NULL,
	stophour time NOT NULL,
	startinterval time NULL,
	workingdays _text NULL,
	intervalduration int4 NULL,
	CONSTRAINT newtable_pk PRIMARY KEY (id),
	CONSTRAINT employees_images_fk FOREIGN KEY (imageid) REFERENCES public.images(id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT employees_shops_fk FOREIGN KEY (shopid) REFERENCES public.shops(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Permissions

ALTER TABLE public.employees OWNER TO postgres;
GRANT ALL ON TABLE public.employees TO postgres;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.employees TO dev;


-- public.ratings definição

-- Drop table

-- DROP TABLE public.ratings;

CREATE TABLE public.ratings (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"comment" text NULL,
	userid int4 NOT NULL,
	shopid int4 NOT NULL,
	value int4 DEFAULT 0 NOT NULL,
	"date" date DEFAULT CURRENT_DATE NOT NULL,
	images _int4 NULL,
	CONSTRAINT ratings_pk PRIMARY KEY (id),
	CONSTRAINT ratings_shops_fk FOREIGN KEY (shopid) REFERENCES public.shops(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT ratings_users_fk FOREIGN KEY (userid) REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Permissions

ALTER TABLE public.ratings OWNER TO postgres;
GRANT ALL ON TABLE public.ratings TO postgres;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.ratings TO dev;


-- public.schedules definição

-- Drop table

-- DROP TABLE public.schedules;

CREATE TABLE public.schedules (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"date" timestamp NOT NULL,
	employeeid int4 NOT NULL,
	duration int4 NOT NULL,
	userid int4 NOT NULL,
	CONSTRAINT schedule_pk PRIMARY KEY (id),
	CONSTRAINT schedule_employees_fk FOREIGN KEY (employeeid) REFERENCES public.employees(id) ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT schedule_users_fk FOREIGN KEY (userid) REFERENCES public.users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Permissions

ALTER TABLE public.schedules OWNER TO postgres;
GRANT ALL ON TABLE public.schedules TO postgres;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.schedules TO dev;


-- public.services definição

-- Drop table

-- DROP TABLE public.services;

CREATE TABLE public.services (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	shopid int4 NOT NULL,
	"name" varchar(256) NOT NULL,
	imageid int4 NULL,
	price numeric(10, 2) NOT NULL,
	duration int4 NOT NULL,
	description text NULL,
	CONSTRAINT services_pk PRIMARY KEY (id),
	CONSTRAINT services_images_fk FOREIGN KEY (imageid) REFERENCES public.images(id) ON DELETE SET NULL ON UPDATE CASCADE,
	CONSTRAINT services_shops_fk FOREIGN KEY (shopid) REFERENCES public.shops(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- Permissions

ALTER TABLE public.services OWNER TO postgres;
GRANT ALL ON TABLE public.services TO postgres;
GRANT INSERT, SELECT, UPDATE, DELETE ON TABLE public.services TO dev;




-- Permissions

GRANT ALL ON SCHEMA public TO pg_database_owner;
GRANT USAGE ON SCHEMA public TO public;